### PR TITLE
Moving amsat-informer to bottom and only last 3 days

### PR DESCRIPTION
**Pull request by int2001**
@phl0 important: remove debug (3445) // activate upload (3446)

### CODE REVIEW

**Comment by phl0** [comment]
Tnx. Will test and report.

**Comment by phl0** [comment]
@int2001 Would you agree with the following change:

```
diff --git a/application/models/Logbook_model.php b/application/models/Logbook_model.php
index 4c6ca0403..f0204338e 100644
--- a/application/models/Logbook_model.php
+++ b/application/models/Logbook_model.php
@@ -3421,7 +3421,8 @@ function lotw_last_qsl_date($user_id) {
                                array_push($a_qsos,$one_error['raw_qso'] ?? '');
                                if (isset($record['prop_mode']) && $record['prop_mode'] == 'SAT' && $amsat_status_upload) {
                                        $amsat_qsodate=new DateTime(date('Y-m-d', strtotime($record['qso_date'])) ." ".date('H:i:s', strtotime($record['time_on'])));
-                                       if ($amsat_qsodate->diff($today)->d <= 3) {
+                                       $date_diff = (int)$amsat_qsodate->diff($today)->format('%r%d');
+                                       if ($date_diff >= 0 && $date_diff <= 5) {
                                                $data = array(
                                                        'COL_TIME_ON' => date('Y-m-d', strtotime($record['qso_date'])) ." ".date('H:i:s', strtotime($record['time_on'])),
                                                        'COL_SAT_NAME' => $record['sat_name'],
```

Does not allow future QSOs to be uploaded (fences everywhere) and QSOs of the past 6 days to be pushed to AMSAT status page. The page shows the last 6 days.

**Comment by int2001** [comment]
yep. seems legit

**Review by phl0 — APPROVED** [review]
Works now based on timestamps.

**Pull request merged**
